### ISSUE TITLE
Uncaught RangeError: index out of range

### ISSUE THREAD

**Issue by forivall** [dchacke/synesthesia#2]
1. Open a markdown file.
2. Enable synesthesia from command palette.
3. Sadness.

**Atom Version**: 1.0.19
**System**: "Manjaro Linux"
**Thrown From**: [synesthesia](https://github.com/dchacke/synesthesia) package, v0.1.1-1
### Stack Trace

Uncaught RangeError: index out of range

```
At buffer.js:819

RangeError: index out of range
  at checkInt (buffer.js:819:11)
  at Buffer.writeInt16LE (buffer.js:975:5)
  at Readable.play.node._read (/home/forivall/.atom/packages/synesthesia/node_modules/timbre/timbre.node.js:39:25)
  at Readable.read (_stream_readable.js:324:10)
  at resume_ (_stream_readable.js:704:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```
### Commands

```
     -0:03.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.0 synesthesia:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "adwaita-ui",
      "atom-color-highlight",
      "atom-ctags",
      "atom-json-escape",
      "atom-terminal",
      "atom-ungit",
      "atomatigit",
      "autocomplete-plus-python-jedi",
      "build-tools",
      "browser-plus",
      "color-picker",
      "command-toolbar",
      "ctags-status",
      "dbus",
      "fixmyjs",
      "git-projects",
      "hide-files",
      "ide-flow",
      "language-babel",
      "linter-clang",
      "linter-coffeescript",
      "linter-flake8",
      "linter-flow",
      "linter-jshint",
      "linter-pep8",
      "linter-pyflakes",
      "linter-pylint",
      "linter-rust",
      "linter-scss-lint",
      "linter-stylint",
      "node-debugger",
      "preview-plus",
      "pigments",
      "recent-files-fuzzy-finder",
      "recent-files",
      "save-session",
      "selection-outlines",
      "sublime-tabs",
      "symbol-gen",
      "switch-header-source",
      "tab-length",
      "tomorrow",
      "webbox-color",
      "welcome",
      "wrap-guide",
      "wrap",
      "you-complete-me",
      "indent-guide-improved",
      "hyperclick",
      "atom-jinja2",
      "nuclide-type-hint",
      "linter-coffeelint",
      "tree-view-open-files",
      "smart-tab-name"
    ],
    "themes": [
      "adwaita-pro-ui",
      "tomorrow-ya"
    ],
    "packagesWithKeymapsDisabled": [
      "sort-lines"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".imdone",
      "tags",
      "npm-debug.log"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
adwaita-pro-ui, v2.1.1
atom-ternjs, v0.8.2
auto-detect-indentation, v0.4.2
autocomplete-modules, v1.3.0
autocomplete-paths, v1.0.2
cursor-history, v0.5.3
custom-invisibles, v0.1.2
docblockr, v0.7.3
editorconfig, v1.2.0
es-identifier-highlight, v0.2.6
file-icons, v1.6.10
file-types, v0.5.1
fold-functions, v0.4.0
github-notifications, v0.1.1
highlight-selected, v0.10.1
imdone-atom, v1.1.45
language-autotools, v2.0.1
language-cmake, v0.1.4
language-diff, v0.3.1
language-dots, v0.0.4
language-haxe, v0.3.0
language-jade, v0.6.2
language-javascript-better, v1.7.1
language-json5, v1.1.0
language-lua, v0.9.4
language-qml, v1.0.0
language-rust, v0.4.5
language-typescript-grammars-only, v1.3.0
linter, v1.8.1
linter-eslint, v3.1.1
linter-nplint, v0.3.24
linter-shellcheck, v1.0.2
linter-xo, v0.7.1
minimap, v4.13.4
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
multi-wrap-guide, v0.22.3
pane-by-type, v1.0.0
project-manager, v2.6.3
project-view, v0.1.2
remember-file-positions, v0.1.6
run-in-terminal, v0.4.2
symbols-tree-view, v0.10.0
synesthesia, v0.1.1-1
tab-control, v0.6.8
tablr, v0.4.0
term3, v0.19.0
theme-switcher, v1.1.0
tomorrow-ya, v1.0.2
tree-view, v0.189.0
tree-view-breadcrumb, v0.7.0
tree-view-git-projects, v0.5.0

# Dev
No dev packages
```

**Comment by dchacke** [comment]
Did you check the other open issue? This package isn't complete. I'll add a hint to the Readme.

**Comment by forivall** [comment]
Yeah, I just wanted to still check it out, and see what noise it would make. Therefore, "Step 3: Sadness".

**Comment by dchacke** [comment]
Haha!
